### PR TITLE
add new function and fix a issue

### PR DESCRIPTION
**Pull request by hearther**
1. add onUpdateReceivedSize to show how much data is received
2. fix network disconnect and wait unit the buffer ran out then reopen the http_stream to restart the streaming
 
2 is trying to fix issue in following situation
 a. Start to play any web music (streaming or not) but still under data transferring with WIFI only ( other network are disable)
 b. Shut down the WIFI, music is still playing since there are still some buffer can use for playing
 c. Turn on LTE/3G, the network is come back. When the buffer ran out, the streaming doesn't come back 

After my tracing the code I found
when network changed is detected in - (void)reachabilityChanged:(NSNotification *)note and call [self attemptRestart] try to restart the streaming.
In [self attemptRestart] it call "- (void)play".
In "- (void)play" it call _audioStream->open()  try to reopen the audio stream.

void Audio_Stream::open(Input_Stream_Position *position)
{
/// Since the buffer is still running here will return directly
    if (m_inputStreamRunning || m_audioStreamParserRunning) {  
        AS_TRACE("%s: already running: return\n", __PRETTY_FUNCTION__);
        return;
    }

And I don't want to waste the buffer, so I added the code to retry after the buffer ran out.

### CODE REVIEW

**Comment by syrakozz** [comment]
+1

**Comment by muhku** [comment]
Checked the code. Please, in the future, only one change per commit. Difficult to check what to merge when there are many changes.

I don't want to merge this one. If I understood the logic correctly, it disconnects the network if the stream buffers for a single time. This is not acceptable to me. Many times the network can still recover and give more data. You could achieve the same behavior by just setting maxBounceCount = 1 in the configuration.

**Comment by muhku** [comment]
I think I encountered the problem this Pull Request attempted to fix. Try pulling the commits 1a65e7a347990998b2d5070f786e1469bc48634b and e3c1f93169ec2263daaa6913feb42eeaa9508c30 if it helps. If the network is not providing enough data, these two commits should make sure, that the stream tries to keep restarting instead of getting stuck in the buffering state.

**Comment by hearther** [comment]
Hi,

Sorry to make you different to merged.
I had tried to split the feature(#177) to different pull request.
And I will try the commits  1a65e7a and e3c1f93.

**Pull request closed without merging**
