### PR TITLE
fix playFromOffset NOT play when preloading

### PR DESCRIPTION
**Pull request by IvanChan**
1. reset _wasPaused
2. judge if preloading

### CODE REVIEW

**Comment by muhku** [comment]
Please keep a single PR so that it doesn't touch a bunch of other areas in single commits. Are  a435948 and 445edab related to the fix?

About the fix (eb492c6), does it work so that playback is resumed from the given offset? I didn't test but to me it was uncertain if that is the case based on the code.

**Comment by IvanChan** [comment]
Firstly I add autoSeek feature for FSAudioController, **445edab**, 
**bedaa1c** to add a property to control this feature, disabled by default.

Then I met 2 bugs:
1) the playFromOffset not reseting wasPaused, the next audio not play if previous is paused
2) if current is playing, next is preloading, click next to play, next audio play ran into assert(stream is already running), but actually not going to play.

so, **eb492c6** is try to fix 2 bugs above.

**a435948** is just add a property for playrate, so user can change rate for fun.

**Comment by muhku** [comment]
OK. More clear now. I don't think eb492c6 starts playback from correct position.

My attempt is in ee4cc3c, can you check if that fixes the problem for you?

**Comment by IvanChan** [comment]
Bravo, I test it a little bit,  your way is definitely better.

**Comment by muhku** [comment]
FYI: also added the audioDataByteCount property, which may be useful.

**Pull request closed without merging**
