### PR TITLE
fix retry when network error happen in the very first time buffing

### PR DESCRIPTION
**Pull request by hearther**
Issue happen is following steps
1. Start to play a URL for the very first time.
2. When start to buffering the audio, and network error occurs.
3. It won't retry for 3 times, freestreamer will directly fail.

### CODE REVIEW

**Comment by syrakozz** [comment]
+1 its an important fix

**Comment by muhku** [comment]
This looks like a reasonable change. One major problem though. In commit 6247d649e6ebcb6d7f13ca198fb4f038398abcd5 notifyStateChange is called directly without a timer. This means, that the block based onStateHandlers will be executed before the player has a chance to complete in the event loop. Depending on the onStateHandler it can mean that the player is a weird state waiting for the onStateHandler to complete. This has caused issues before, so please call notifyStateChange with a timer like this:

<pre>
    // Detach from the player so that the event loop can complete its cycle.
    // This ensures that the stream gets closed, if needs to be.
    [NSTimer scheduledTimerWithTimeInterval:0.1
                                     target:priv
                                   selector:notificationHandler
                                   userInfo:nil
                                    repeats:NO];
</pre>

A minor style issue is that instead of setRetryCount / retryCount in the public FSAudioStream interface, why not to have a single retryCount property? This would be a cleaner interface to the users:

<pre>
@property (nonatomic,assign) NSUInteger maxRetryCount;
</pre>

**Comment by muhku** [comment]
Did the changes in commit 1b048be9d22b50b08148e82875ac3c4d373a8417 so no need to merge this Pull Request directly.

Thanks!

**Comment by hearther** [comment]
Sorry for late reply, I had been in Chinese new year vacation.
Sure, your commit is better than me, especially in "setRetryCount / retryCount".

**Pull request closed without merging**
